FROM pytorch/pytorch

WORKDIR app

COPY misc/data misc/data
COPY requirements.txt requirements.txt
COPY train.py train.py

RUN pip install -r requirements.txt

CMD ["python", "train.py", "-f", "/app/docker_artifacts/resnet18_model.pt"]